<?xml version="1.0" encoding="utf-8"?><Database Name="Database" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Database.mdf;Integrated Security=True" SettingsObjectName="PortfolioManagement.Properties.Settings" SettingsPropertyName="DatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="money" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="User_Stock" Member="Stocks" ThisKey="id" OtherKey="User_id" Type="Stock" />
    </Type>
  </Table>
  <Table Name="dbo.Stocks" Member="Stocks">
    <Type Name="Stock">
      <Column Name="Transaction_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="User_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="stock_symbol" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="count" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="purchasePrice" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="User_Stock" Member="User" ThisKey="User_id" OtherKey="id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
</Database>